### ISSUE TITLE
cpuinfo parser can not handle s390 /proc/cpuinfo

### ISSUE THREAD

**Issue by chenlizhong** [RedHatInsights/insights-core#2977] opened 2021-03-11 08:21 UTC
s390:

> vendor_id       : IBM/S390
# processors    : 4
bogomips per cpu: 3033.00
max thread id   : 0
features	: esan3 zarch stfle msa ldisp eimm dfp edat etf3eh highgprs te vx sie 
facilities      : 0 1 2 3 4 6 7 8 9 10 12 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 30 31 32 33 34 35 36 37 40 41 42 43 44 45 46 47 48 49 50 51 52 53 55 57 73 74 75 76 77 80 81 82 128 129
cache0          : level=1 type=Data scope=Private size=128K line_size=256 associativity=8
cache1          : level=1 type=Instruction scope=Private size=96K line_size=256 associativity=6
cache2          : level=2 type=Data scope=Private size=2048K line_size=256 associativity=8
cache3          : level=2 type=Instruction scope=Private size=2048K line_size=256 associativity=8
cache4          : level=3 type=Unified scope=Shared size=65536K line_size=256 associativity=16
cache5          : level=4 type=Unified scope=Shared size=491520K line_size=256 associativity=30
processor 0: version = FF,  identification = 0133E8,  machine = 2964
processor 1: version = FF,  identification = 0133E8,  machine = 2964
processor 2: version = FF,  identification = 0133E8,  machine = 2964
processor 3: version = FF,  identification = 0133E8,  machine = 2964

cpu number      : 0
cpu MHz dynamic : 5000
cpu MHz static  : 5000

cpu number      : 1
cpu MHz dynamic : 5000
cpu MHz static  : 5000

cpu number      : 2
cpu MHz dynamic : 5000
cpu MHz static  : 5000

cpu number      : 3
cpu MHz dynamic : 5000
cpu MHz static  : 5000

**Comment by xiangce** [comment] 2021-03-12 01:14
I believe this is a duplicate of the #2629

**Comment by bfahr** [comment] 2021-04-06 16:09
Closing this bug as its a duplicate of #2629

**Closed by bfahr** 2021-04-06 16:09 UTC
Labels: bug
