### ISSUE TITLE
Unable to inspect  insights.combiners.ps.Ps

### ISSUE THREAD

**Issue by rameshsahoo111** [RedHatInsights/insights-core#2880] opened 2021-01-08 07:17 UTC
(gss-rules) ⌊gss-rules⌋»$ insights inspect insights.combiners.ps.Ps ~/scripts/rhel7_sosreport/
Traceback (most recent call last):
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/core/dr.py", line 962, in run
    result = DELEGATES[component].process(broker)
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/core/dr.py", line 681, in process
    return self.invoke(broker)
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/core/plugins.py", line 64, in invoke
    return super(PluginType, self).invoke(broker)
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/core/dr.py", line 661, in invoke
    return self.component(*args)
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/combiners/ps.py", line 125, in __init__
    self.__convert_data_types()
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/combiners/ps.py", line 260, in __convert_data_types
    for attr_name in self.__CONVERSION_MAP
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/combiners/ps.py", line 262, in <listcomp>
    if attr_name in row]
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/combiners/ps.py", line 257, in convert_attr
    row[attr_name] = type_ctor(row[attr_name])
ValueError: could not convert string to float: '11:29'

Traceback (most recent call last):
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/core/dr.py", line 962, in run
    result = DELEGATES[component].process(broker)
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/core/dr.py", line 681, in process
    return self.invoke(broker)
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/core/plugins.py", line 64, in invoke
    return super(PluginType, self).invoke(broker)
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/core/dr.py", line 661, in invoke
    return self.component(*args)
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/combiners/ps.py", line 125, in __init__
    self.__convert_data_types()
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/combiners/ps.py", line 260, in __convert_data_types
    for attr_name in self.__CONVERSION_MAP
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/combiners/ps.py", line 262, in <listcomp>
    if attr_name in row]
  File "/home/rsahoo/PycharmProjects/Python/redhat/gss-rules/lib64/python3.6/site-packages/insights/combiners/ps.py", line 257, in convert_attr
    row[attr_name] = type_ctor(row[attr_name])
ValueError: could not convert string to float: '11:29'

**Comment by bfahr** [comment] 2021-01-12 14:32
Closing as a duplicate of #2886 which has more information.

**Closed by bfahr** 2021-01-12 14:32 UTC
