### ISSUE TITLE
Parser error in `cluster_conf.py`

### ISSUE THREAD

**Issue by miclark** [RedHatInsights/insights-core#679] opened 2017-11-03 22:56 UTC
Testing against production archives, the following exception occurred 20 times:
```
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 635, in run
    result = DELEGATES[component](broker)
  File "build/bdist.linux-x86_64/egg/insights/core/dr.py", line 594, in __f
    return executor(func, broker, requires, optional)
  File "build/bdist.linux-x86_64/egg/insights/core/plugins.py", line 29, in parser_executor
    return component(dep_value)
  File "build/bdist.linux-x86_64/egg/insights/parsers/cluster_conf.py", line 150, in get_cluster_conf
    cluster_xml = ET.fromstring("\n".join(context.content))
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    return parser.close()
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1654, in close
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: no element found: line 6, column 27
```

**Comment by csams** [comment] 2018-02-17 16:36
Duplicate of #785. Fixed in #777 and #743.

**Closed by csams** 2018-02-17 16:36 UTC
Labels: bug
